"""Central export for all modular prompt definitions."""
from src.prompts.coordinator_prompts import (
    COORDINATOR_SYSTEM_PROMPT,
    COORDINATOR_USER_PROMPT_TEMPLATE,
)
from src.prompts.draft_prompts import (
    SYSTEM_PROMPT as DRAFT_SYSTEM_PROMPT,
    USER_PROMPT_TEMPLATE as DRAFT_USER_PROMPT_TEMPLATE,
)
from src.prompts.fluency_prompts import (
    SYSTEM_PROMPT as FLUENCY_SYSTEM_PROMPT,
    USER_PROMPT_TEMPLATE as FLUENCY_USER_PROMPT_TEMPLATE,
)
from src.prompts.intent_prompts import (
    INTENT_CLASSES,
    SYSTEM_PROMPT as INTENT_SYSTEM_PROMPT,
    USER_PROMPT_TEMPLATE as INTENT_USER_PROMPT_TEMPLATE,
)
from src.prompts.rag_prompts import (
    SYSTEM_PROMPT as RAG_SYSTEM_PROMPT,
    USER_PROMPT_TEMPLATE as RAG_USER_PROMPT_TEMPLATE,
)
from src.prompts.urgency_prompts import (
    SYSTEM_PROMPT as URGENCY_SYSTEM_PROMPT,
    USER_PROMPT_TEMPLATE as URGENCY_USER_PROMPT_TEMPLATE,
)

__all__ = [
    "FLUENCY_SYSTEM_PROMPT",
    "FLUENCY_USER_PROMPT_TEMPLATE",
    "INTENT_SYSTEM_PROMPT",
    "INTENT_CLASSES",
    "INTENT_USER_PROMPT_TEMPLATE",
    "URGENCY_SYSTEM_PROMPT",
    "URGENCY_USER_PROMPT_TEMPLATE",
    "RAG_SYSTEM_PROMPT",
    "RAG_USER_PROMPT_TEMPLATE",
    "DRAFT_SYSTEM_PROMPT",
    "DRAFT_USER_PROMPT_TEMPLATE",
    "COORDINATOR_SYSTEM_PROMPT",
    "COORDINATOR_USER_PROMPT_TEMPLATE",
]
